name: aiascs_mobile
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences:
  flutter_svg: 
  google_fonts: 
  http: 
  sqflite:
  path:
  provider: 
  qrscan: ^0.2.22
  socket_io_client: ^0.9.12
  fluttertoast: ^7.0.4
  adhara_socket_io: ^0.4.2+1
  badges: ^1.2.0
  pie_chart: ^5.0.0
  connectivity: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  